---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: ".github/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "weekly"
